[theme]
primaryColor = "#B4232F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F5F8"
textColor = "#18212F"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

